sonar.projectKey=qa-capsule-community
sonar.projectName=QA Capsule Community
sonar.projectVersion=1.0.17-beta

sonar.sources=cmd,pkg
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/web/**,**/tests/**,**/docs/**,**/plugins/**,**/images/**,**/*.md

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
